### ISSUE TITLE
Favicon not refreshed after file updated

### ISSUE THREAD

**Issue by jainesh-0xblock** [faviconkit/javascript-api#19]
Hello 

We have updated favicon file but it's not updating on metamask mobile and showing older favicon only.

Please check it ASAP and fix it

**Comment by jainesh-0xblock** [comment]
@AndreasPizsa Please check this on priority please...Issue is https://breakable-moccasin-bug.faviconkit.com/{domain}/64 always shows cached version although we have updated favicon

**Comment by jainesh-0xblock** [comment]
@AndreasPizsa 

We are using this URL

Domain - https://basedswap.exchange


Cached Version - https://breakable-moccasin-bug.faviconkit.com/basedswap.exchange/64
Expected result for above URL - https://breakable-moccasin-bug.faviconkit.com/basedswap.exchange?v1/64

**Comment by andreaspitzer** [comment]
Done. To see the change in your browser, make sure you refresh with browser caching disabled (hold shift while reloading).

**Comment by jainesh-0xblock** [comment]
Thanks @AndreasPizsa

**Comment by jainesh-0xblock** [comment]
@AndreasPizsa It still shows older image for 50 - https://api.faviconkit.com/basedswap.exchange/50. Can you please clear cache for all size ASAP

**Comment by jainesh-0xblock** [comment]
@AndreasPizsa Can you please do it ASAP

**Comment by matukosan** [comment]
@jainesh-0xblock should be fixed

**Comment by dev-stark-017** [comment]
same issue with domain twitter: https://api.faviconkit.com/twitter.com/50

**Comment by imaksp** [comment]
@rd-stark you can try creating new issue here with details:
https://github.com/faviconkit/javascript-api/issues
